version: '3'

services:

  website:
    image: cod4it/web.wepromolink:1.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/wepromolink.com/:/etc/nginx/ssl/:ro,Z
      - ./certbot/data:/etc/nginx/ssl/challenge

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: >-
            certonly --reinstall --webroot --webroot-path=/var/www/certbot
            --email jose.devops@gmail.com --agree-tos --no-eff-email
            -d wepromolink.com
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot