version: '3'

services:

  website:
    image: cod4it/web.wepromolink:1.0
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - /etc/letsencrypt/archive/wepromolink.com/:/etc/nginx/ssl/:ro,Z