name: Web.WepromoLink API Pipeline
on:
  push:
    branches:
      - dev
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Install jq
        run: sudo apt-get install jq

      - name: Read version file and set environment variables
        run: |
          versions=$(cat versions.json)
          echo "$versions" | jq -r 'to_entries | .[] | "MICROSERVICE_\(.key | ascii_upcase)=\(.value)"' >> $GITHUB_ENV      
        
      - name: Build and Push Docker Image Web.WePromolink
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cod4it/web.wepromolink:${{ env.MICROSERVICE_WEB }}

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WEPROMOLINK_DEV_HOST }}
          username: ${{ secrets.WEPROMOLINK_DEV_USERNAME }}
          password: ${{ secrets.WEPROMOLINK_DEV_PASSWORD }}
          script:  |
            cd code
            cd web.wepromolink.com/
            git pull
            git checkout dev
            cd K8s/
            cd Dev/
            versions=$(cat ../../versions.json)
            readarray -t versions <<< "$(echo "$versions" | jq -r 'to_entries | .[] | "MICROSERVICE_\(.key | ascii_upcase)=\(.value)"')"; for v in "${versions[@]}"; do export "$v"; done
            envsubst < wepromolink_dev.yml > wepromolink_dev_ready.yml
            microk8s kubectl apply -f wepromolink_dev_ready.yml
    
